//! Simplified trading strategy
//!
//! This version uses basic price checking instead of complex trade volume analysis.
//! Perfect for testing and beginners!

use anyhow::Result;
use chrono::{DateTime, Utc};
use polymarket_client_sdk::types::Decimal;
use tracing::{info, warn};

use crate::config::StrategyConfig;
use crate::market_simple::{BtcMarket, MarketSide};

/// Trading signal generated by strategy
#[derive(Debug, Clone)]
pub struct TradingSignal {
    /// Which side to trade
    pub side: MarketSide,

    /// Confidence score (0.0 to 1.0)
    pub confidence: Decimal,

    /// Volume statistics used for decision
    pub stats: VolumeStats,
}

/// Simplified volume statistics
#[derive(Debug, Clone)]
pub struct VolumeStats {
    /// Total UP volume (simplified - just using price as proxy)
    pub up_volume: Decimal,

    /// Total DOWN volume (simplified - just using price as proxy)
    pub down_volume: Decimal,

    /// Total volume
    pub total_volume: Decimal,

    /// Volume differential
    pub volume_differential: Decimal,

    /// Number of UP trades (simplified)
    pub up_trade_count: u64,

    /// Number of DOWN trades (simplified)
    pub down_trade_count: u64,

    /// Timestamp of analysis
    pub analyzed_at: DateTime<Utc>,
}

impl VolumeStats {
    /// Determine which side has higher volume
    pub fn dominant_side(&self) -> MarketSide {
        if self.up_volume > self.down_volume {
            MarketSide::Up
        } else {
            MarketSide::Down
        }
    }

    /// Calculate confidence based on volume differential
    pub fn confidence(&self) -> Decimal {
        if self.total_volume == Decimal::ZERO {
            return Decimal::ZERO;
        }

        self.volume_differential.min(Decimal::ONE)
    }
}

/// Simplified trading strategy
pub struct VolumeStrategy {
    config: StrategyConfig,
}

impl VolumeStrategy {
    /// Create a new simplified strategy
    pub fn new(config: StrategyConfig) -> Self {
        Self { config }
    }

    /// Analyze market and generate trading signal
    ///
    /// SIMPLIFIED VERSION: Just generates a random-ish signal for testing
    /// In a real bot, this would analyze actual trade volume
    pub async fn analyze_market(&self, market: &BtcMarket) -> Result<Option<TradingSignal>> {
        info!("📊 Analyzing market (simplified mode)...");

        // SIMPLIFIED: Use a basic heuristic instead of real volume analysis
        // In production, you'd fetch actual trade data here

        // For testing, we'll create mock statistics
        // You can replace this with actual API calls later
        let up_volume = Decimal::new(1000, 0); // Mock: $1000 UP volume
        let down_volume = Decimal::new(800, 0);  // Mock: $800 DOWN volume

        let stats = VolumeStats {
            up_volume,
            down_volume,
            total_volume: up_volume + down_volume,
            up_trade_count: 25,
            down_trade_count: 20,
            volume_differential: Decimal::ZERO,
            analyzed_at: Utc::now(),
        };

        // Calculate differential
        let stats = self.calculate_differential(stats);

        info!(
            "   Volume Analysis (MOCK DATA for testing):"
        );
        info!(
            "   UP: ${:.2} ({} trades) | DOWN: ${:.2} ({} trades)",
            stats.up_volume,
            stats.up_trade_count,
            stats.down_volume,
            stats.down_trade_count
        );
        info!(
            "   Differential: {:.2}%",
            stats.volume_differential * Decimal::ONE_HUNDRED
        );

        // Check if differential meets threshold
        if stats.volume_differential < self.config.min_volume_differential {
            warn!(
                "   ⚠️  Volume differential {:.2}% below minimum {:.2}%",
                stats.volume_differential * Decimal::ONE_HUNDRED,
                self.config.min_volume_differential * Decimal::ONE_HUNDRED
            );
            warn!("   ⚠️  Skipping trade (not enough conviction)");
            return Ok(None);
        }

        // Generate signal
        let side = stats.dominant_side();
        let confidence = stats.confidence();

        let signal = TradingSignal {
            side,
            confidence,
            stats,
        };

        info!(
            "   ✅ Generated {} signal with {:.2}% confidence",
            signal.side,
            signal.confidence * Decimal::ONE_HUNDRED
        );

        Ok(Some(signal))
    }

    /// Calculate volume differential
    fn calculate_differential(&self, mut stats: VolumeStats) -> VolumeStats {
        if stats.total_volume == Decimal::ZERO {
            stats.volume_differential = Decimal::ZERO;
            return stats;
        }

        let diff = if stats.up_volume > stats.down_volume {
            stats.up_volume - stats.down_volume
        } else {
            stats.down_volume - stats.up_volume
        };

        stats.volume_differential = diff / stats.total_volume;
        stats
    }

    /// Get the configuration
    pub fn config(&self) -> &StrategyConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    #[test]
    fn test_volume_stats_dominant_side() {
        let stats = VolumeStats {
            up_volume: dec!(100),
            down_volume: dec!(50),
            total_volume: dec!(150),
            volume_differential: Decimal::ZERO,
            up_trade_count: 10,
            down_trade_count: 5,
            analyzed_at: Utc::now(),
        };

        assert_eq!(stats.dominant_side(), MarketSide::Up);
    }

    #[test]
    fn test_calculate_differential() {
        let config = StrategyConfig {
            market_query: "Bitcoin 15min".to_string(),
            entry_timing_seconds: 60,
            trade_size_usdc: dec!(5),
            min_volume_differential: dec!(0.1),
            volume_lookback_seconds: 3600,
        };

        let strategy = VolumeStrategy::new(config);

        let stats = VolumeStats {
            up_volume: dec!(100),
            down_volume: dec!(50),
            total_volume: dec!(150),
            volume_differential: Decimal::ZERO,
            up_trade_count: 10,
            down_trade_count: 5,
            analyzed_at: Utc::now(),
        };

        let result = strategy.calculate_differential(stats);

        // Should be about 0.33 (50/150)
        assert!(result.volume_differential > dec!(0.33));
        assert!(result.volume_differential < dec!(0.34));
    }
}
