//! Trading strategy implementation
//!
//! This module implements the volume-based trading strategy:
//! - Analyze recent trade volume for UP vs DOWN
//! - Generate trading signals based on volume differential

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use polymarket_client_sdk::clob::Client;
use polymarket_client_sdk::clob::types::request::TradesRequest;
use polymarket_client_sdk::clob::types::Side;
use rust_decimal::Decimal;
use std::collections::HashMap;
use tracing::{debug, info, warn};

use crate::config::StrategyConfig;
use crate::market::{BtcMarket, MarketSide};

/// Trading signal generated by strategy
#[derive(Debug, Clone)]
pub struct TradingSignal {
    /// Which side to trade
    pub side: MarketSide,

    /// Confidence score (0.0 to 1.0)
    pub confidence: Decimal,

    /// Volume statistics used for decision
    pub stats: VolumeStats,
}

/// Volume statistics for a market
#[derive(Debug, Clone)]
pub struct VolumeStats {
    /// Total UP volume (in USDC)
    pub up_volume: Decimal,

    /// Total DOWN volume (in USDC)
    pub down_volume: Decimal,

    /// Total volume (UP + DOWN)
    pub total_volume: Decimal,

    /// Volume differential (|UP - DOWN| / total)
    pub volume_differential: Decimal,

    /// Number of UP trades
    pub up_trade_count: u64,

    /// Number of DOWN trades
    pub down_trade_count: u64,

    /// Timestamp of analysis
    pub analyzed_at: DateTime<Utc>,
}

impl VolumeStats {
    /// Determine which side has higher volume
    pub fn dominant_side(&self) -> MarketSide {
        if self.up_volume > self.down_volume {
            MarketSide::Up
        } else {
            MarketSide::Down
        }
    }

    /// Calculate confidence based on volume differential
    pub fn confidence(&self) -> Decimal {
        if self.total_volume == Decimal::ZERO {
            return Decimal::ZERO;
        }

        // Confidence is the volume differential clamped to [0, 1]
        self.volume_differential.min(Decimal::ONE)
    }
}

/// Volume-based trading strategy
pub struct VolumeStrategy {
    client: Client,
    config: StrategyConfig,
}

impl VolumeStrategy {
    /// Create a new volume strategy
    pub fn new(client: Client, config: StrategyConfig) -> Self {
        Self { client, config }
    }

    /// Analyze market volume and generate trading signal
    ///
    /// This method fetches recent trades for the market and calculates
    /// volume statistics to determine which side (UP or DOWN) to trade.
    pub async fn analyze_market(&self, market: &BtcMarket) -> Result<Option<TradingSignal>> {
        info!("Analyzing market: {}", market.question);

        // Fetch recent trades for both UP and DOWN tokens
        let up_stats = self.fetch_token_volume(&market.up_token_id).await?;
        let down_stats = self.fetch_token_volume(&market.down_token_id).await?;

        // Combine statistics
        let stats = VolumeStats {
            up_volume: up_stats.0,
            down_volume: down_stats.0,
            total_volume: up_stats.0 + down_stats.0,
            up_trade_count: up_stats.1,
            down_trade_count: down_stats.1,
            volume_differential: Decimal::ZERO, // Calculate below
            analyzed_at: Utc::now(),
        };

        // Calculate volume differential
        let stats = self.calculate_differential(stats);

        info!(
            "Volume Analysis | UP: ${:.2} ({} trades) | DOWN: ${:.2} ({} trades) | Diff: {:.2}%",
            stats.up_volume,
            stats.up_trade_count,
            stats.down_volume,
            stats.down_trade_count,
            stats.volume_differential * Decimal::ONE_HUNDRED
        );

        // Check if volume differential meets minimum threshold
        if stats.volume_differential < self.config.min_volume_differential {
            warn!(
                "Volume differential {:.2}% below minimum threshold {:.2}%",
                stats.volume_differential * Decimal::ONE_HUNDRED,
                self.config.min_volume_differential * Decimal::ONE_HUNDRED
            );
            return Ok(None);
        }

        // Check if there's sufficient volume
        if stats.total_volume == Decimal::ZERO {
            warn!("No volume detected in lookback period");
            return Ok(None);
        }

        // Generate signal
        let side = stats.dominant_side();
        let confidence = stats.confidence();

        let signal = TradingSignal {
            side,
            confidence,
            stats,
        };

        info!(
            "Generated signal: {} with {:.2}% confidence",
            signal.side,
            signal.confidence * Decimal::ONE_HUNDRED
        );

        Ok(Some(signal))
    }

    /// Fetch volume for a specific token
    ///
    /// Returns (total_volume_usdc, trade_count)
    async fn fetch_token_volume(&self, token_id: &str) -> Result<(Decimal, u64)> {
        debug!("Fetching volume for token: {}", token_id);

        // Calculate lookback timestamp
        let lookback = Utc::now()
            - chrono::Duration::seconds(self.config.volume_lookback_seconds as i64);

        // Fetch trades for this token
        let params = TradesRequest::builder()
            .asset_id(token_id.to_string())
            .after(lookback.timestamp())
            .build();

        let mut total_volume = Decimal::ZERO;
        let mut trade_count = 0u64;

        // Fetch trades with pagination
        let mut next_cursor = None;

        loop {
            let response = self
                .client
                .trades(&params, next_cursor)
                .await
                .context("Failed to fetch trades")?;

            // Process trades
            for trade in &response.data {
                // Calculate trade volume in USDC
                // Trade price is in decimal format (0-1 for binary outcomes)
                // Size is in contract units
                let price = trade.price;
                let size = trade.size;

                // Volume = price * size (for UP) or (1 - price) * size (for DOWN)
                // Actually, size is already in USD terms for Polymarket
                let volume = size;

                total_volume += volume;
                trade_count += 1;
            }

            // Check if there are more pages
            if let Some(cursor) = response.next_cursor {
                if !cursor.is_empty() {
                    next_cursor = Some(cursor);
                } else {
                    break;
                }
            } else {
                break;
            }

            // Safety limit to avoid infinite loops
            if trade_count > 10000 {
                warn!("Reached maximum trade fetch limit (10000)");
                break;
            }
        }

        debug!(
            "Token {} volume: ${:.2} ({} trades)",
            token_id, total_volume, trade_count
        );

        Ok((total_volume, trade_count))
    }

    /// Calculate volume differential
    fn calculate_differential(&self, mut stats: VolumeStats) -> VolumeStats {
        if stats.total_volume == Decimal::ZERO {
            stats.volume_differential = Decimal::ZERO;
            return stats;
        }

        // Differential = |UP - DOWN| / Total
        let diff = if stats.up_volume > stats.down_volume {
            stats.up_volume - stats.down_volume
        } else {
            stats.down_volume - stats.up_volume
        };

        stats.volume_differential = diff / stats.total_volume;
        stats
    }

    /// Get the configuration
    pub fn config(&self) -> &StrategyConfig {
        &self.config
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rust_decimal_macros::dec;

    #[test]
    fn test_volume_stats_dominant_side() {
        let stats = VolumeStats {
            up_volume: dec!(100),
            down_volume: dec!(50),
            total_volume: dec!(150),
            volume_differential: Decimal::ZERO,
            up_trade_count: 10,
            down_trade_count: 5,
            analyzed_at: Utc::now(),
        };

        assert_eq!(stats.dominant_side(), MarketSide::Up);
    }

    #[test]
    fn test_calculate_differential() {
        let client = Client::new("https://clob.polymarket.com", Default::default()).unwrap();
        let config = StrategyConfig {
            market_query: "Bitcoin 15min".to_string(),
            entry_timing_seconds: 60,
            trade_size_usdc: dec!(5),
            min_volume_differential: dec!(0.1),
            volume_lookback_seconds: 3600,
        };

        let strategy = VolumeStrategy::new(client, config);

        let stats = VolumeStats {
            up_volume: dec!(100),
            down_volume: dec!(50),
            total_volume: dec!(150),
            volume_differential: Decimal::ZERO,
            up_trade_count: 10,
            down_trade_count: 5,
            analyzed_at: Utc::now(),
        };

        let result = strategy.calculate_differential(stats);

        // Differential should be |100 - 50| / 150 = 50 / 150 = 0.333...
        assert!(result.volume_differential > dec!(0.33));
        assert!(result.volume_differential < dec!(0.34));
    }
}
